source 'https://github.com/CocoaPods/Specs'
#source 'ssh://git@gitlab.xgt588.com:2222/ios/dxspecs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

inhibit_all_warnings!

target 'Test' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks  
use_frameworks!
  # Pods for Test

  	pod 'Aspects', '~> 1.4.1' 
    pod "JLRoutes"  
pod 'QMUIKit', '~> 4.0.2'
end
 
